# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

use_frameworks!

target 'PowerUpSwift_Example' do
  pod 'PowerUpSwift', :path => '../'

  target 'PowerUpSwift_Tests' do
    inherit! :search_paths

    
  end
end
